Upload page replacement algorithm for fifo #7
fabibec/page-replace-visualizer pull request #11
Opened 2023-12-02 14:44 UTC by masterYoda8

2023-12-03 13:26 UTC, fabibec reviewed
The results are correct, however I'm not sure if the list order is correct at all times, where all the frames should move one position to the right if a new one is inserted. Therefore, I want to propose an alternative solution for you to check out:
```python
def fifo2(frames, reference_string):
    from collections import deque
    frame_list = deque([None]*frames,maxlen=frames)
    page_faults = 0
    for i in reference_string:
        if i not in frame_list:
            # Catch the removed frame if needed
            out = frame_list.pop()
            frame_list.appendleft(i)
            page_faults += 1
        print(frame_list)   
    return page_faults
```

2023-12-04 21:07 UTC, fabibec approved these changes
Nice!

2023-12-09 14:54 UTC, xgsngxguy approved these changes

2023-12-09 14:54 UTC, xgsngxguy commented on fifo.py
simple but functional, good proposal from @fabibec 

in bavaria we say: 'ausgfuxts buerschal'

2023-12-09 14:55 UTC, xgsngxguy requested changes
please merge in dev

2023-12-09 15:00 UTC, merged